package com.salvaceloisma.tfg.enumerados;

public enum EstadoSolicitud {
    PENDIENTE_ACEPTAR_JEFATURA,
    PENDIENTE_ADJUNTAR_ARCHIVO_PROFESOR,
    PENDIENTE_FIRMA_DIRECCION,
    PENDIENTE_FIRMA_JEFATURA_EDUCACION,
    FINALIZADO_DIRECCION_ACEPTO_CORREO
}

