package com.salvaceloisma.tfg.enumerados;

//ENUMERADO PARA LOS DISTINTOS ESTADOS Y PODER DIFERENCIAR DONDE ESTA CADA SOLICITUD
public enum EstadoSolicitud {
    PENDIENTE_FIRMA_JEFATURA,
    RECHAZADO_JEFATURA,
    APROBADO_JEFATURA_PDF,
    PENDIENTE_FIRMA_DIRECCION,
    RECHAZADO_DIRECCION,
    SOLICITUD_FINALIZADA
}
